version: "3"
services:
  api:
    image: openbankproject/obp-api
    env_file: api.env
    volumes:
      - "./db:/var/lib/jetty/db:Z"
    ports:
      - "8080:8080"
  api-explorer:
    image: openbankproject/api-explorer
    env_file: api-explorer.env
    ports:
      - "8081:8080"
  api-manager:
    image: openbankproject/api-manager
    env_file: api-manager.env
    ports:
      - "8082:8000"

